import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {DeletedItem,InvoiceDraft,InvoiceLine,Job,Rate,Review,ShootCategory,ShootSort,SyncState} from '../server/types';
import {InvoiceSuggestions,RateCatalog,ReviewSorter} from './WorkflowPanels';
import {orderedItems,shortCalendarName} from './review-display';
import './style.css';
type Data={jobs:Job[];reviews:Review[];invoices:InvoiceDraft[];sorts:ShootSort[];deletedItems:DeletedItem[];rates:Rate[];connections:SyncState[];mode:string;snapshotNote:string;calendarConnected:boolean;gmailConnected:boolean;googleConfigured:boolean;secondaryBackupConfigured:boolean;now:string;lastBackup:string|null};
type View='Overview'|'Jobs'|'Review'|'Invoices'|'Rates'|'Recently Deleted'|'Connections';
const zone='America/Vancouver';
const date=(v:string,options:Intl.DateTimeFormatOptions={day:'numeric',month:'short'})=>new Intl.DateTimeFormat('en-CA',{...options,timeZone:zone}).format(new Date(v.length===10?v+'T12:00:00-07:00':v));
const day=(v:string)=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:zone}).format(new Date(v));
const age=(v:string|null,now:number)=>{if(!v)return 'Never';const minutes=Math.max(0,Math.floor((now-Date.parse(v))/60000));return minutes<1?'Just now':minutes<60?`${minutes} min ago`:minutes<1440?`${Math.floor(minutes/60)} hours ago`:`${Math.floor(minutes/1440)} days ago`;};
const money=(cents:number,currency:'CAD'|'USD')=>new Intl.NumberFormat('en-CA',{style:'currency',currency}).format(cents/100);
const totals=(invoice:InvoiceDraft)=>{const subtotal=invoice.lines.reduce((sum,line)=>sum+line.quantity*line.unitPriceCents,0),tax=invoice.taxTreatment==='taxable'?Math.round(subtotal*invoice.taxRateBps/10000):0;return {subtotal,tax,total:subtotal+tax};};
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-JFM-Request':'1'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'Unable to load this view'),{status:r.status});return data;}
function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={Overview:<><path d="M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z"/></>,Jobs:<><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 2v6m10-6v6M3 11h18"/></>,Review:<><rect x="4" y="3" width="16" height="18" rx="3"/><path d="m8 12 3 3 5-6"/></>,Invoices:<><path d="M6 2h9l3 3v17H6zM9 10h6m-6 4h6m-6 4h4M15 2v4h4"/></>,Rates:<><path d="M4 7h16M4 12h16M4 17h16M8 5v14"/></>, 'Recently Deleted':<><path d="M4 7h16m-14 0 1 14h10l1-14M9 7V4h6v3m-5 4v7m4-7v7"/></>,Connections:<><path d="M8 8h8v8H8zM10 2v6m4-6v6m-4 8v6m4-6v6M2 10h6m-6 4h6m8-4h6m-6 4h6"/></>};return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">{paths[name]}</svg>;}
function InvoiceEditor({invoice,busy,editInvoice,editLine,onSave}:{invoice:InvoiceDraft;busy:boolean;editInvoice:(changes:Partial<InvoiceDraft>)=>void;editLine:(id:string,changes:Partial<InvoiceLine>)=>void;onSave:()=>void}){
 const amount=totals(invoice);
 return <div className="invoice-editor">
  <div className="invoice-fields"><label>Billing client<input value={invoice.client} maxLength={120} onChange={event=>editInvoice({client:event.target.value})}/></label><div className="pricing-control"><span>Whole-invoice pricing</span><div className="pricing-buttons"><button type="button" className="secondary" aria-pressed={invoice.pricingProfileMode==='automatic'} onClick={()=>editInvoice({pricingProfileMode:'automatic'})}>Automatic ({invoice.pricingProfile})</button><button type="button" className="secondary" aria-pressed={invoice.pricingProfileMode==='invoice'&&invoice.pricingProfile==='standard'} onClick={()=>editInvoice({pricingProfileMode:'invoice',pricingProfile:'standard'})}>Use Standard</button><button type="button" className="secondary" aria-pressed={invoice.pricingProfileMode==='invoice'&&invoice.pricingProfile==='legacy'} onClick={()=>editInvoice({pricingProfileMode:'invoice',pricingProfile:'legacy'})}>Use Legacy</button></div><small>Changes the sheet used for matching lines; use Apply all matching sheet prices above to reprice them.</small></div><label>Property or project<input value={invoice.property} maxLength={200} onChange={event=>editInvoice({property:event.target.value})}/></label><label>Approximate square footage<input value={invoice.squareFeet} maxLength={50} placeholder="e.g. 2,400 or Not applicable" onChange={event=>editInvoice({squareFeet:event.target.value})}/></label><label>Currency<select value={invoice.currency} onChange={event=>editInvoice({currency:event.target.value as 'CAD'|'USD'})}><option>CAD</option><option>USD</option></select></label><label>Invoice date<input type="date" value={invoice.invoiceDate} onChange={event=>editInvoice({invoiceDate:event.target.value})}/></label><label>Due date<input type="date" value={invoice.dueDate} onChange={event=>editInvoice({dueDate:event.target.value})}/></label></div>
  <label className="check-field"><input type="checkbox" checked={invoice.completionConfirmed} onChange={event=>editInvoice({completionConfirmed:event.target.checked})}/><span><strong>Completed work confirmed</strong><small>I checked that this shoot occurred and should be invoiced.</small></span></label>
  <div className="invoice-lines"><div className="section-heading"><h3>Invoice lines</h3><button className="text-button" type="button" onClick={()=>editInvoice({lines:[...invoice.lines,{id:`line-${Date.now()}`,description:'',quantity:1,unitPriceCents:0,pricingProfileOverride:null}]})}>Add line</button></div>{invoice.lines.map(line=><div className="invoice-line" key={line.id}><label>Description<input value={line.description} maxLength={160} onChange={event=>editLine(line.id,{description:event.target.value})}/></label><label>Qty<input type="number" min="1" max="100" step="1" value={line.quantity} onChange={event=>editLine(line.id,{quantity:Number(event.target.value)})}/></label><label>Unit price<input type="number" min="0" max="1000000" step="0.01" value={(line.unitPriceCents/100).toFixed(2)} onChange={event=>editLine(line.id,{unitPriceCents:Math.round(Number(event.target.value)*100)})}/></label><button type="button" aria-label={`Remove ${line.description||'invoice line'}`} disabled={invoice.lines.length===1} onClick={()=>editInvoice({lines:invoice.lines.filter(item=>item.id!==line.id)})}>×</button><div className="line-pricing"><span className="caption">Sheet for this item:</span><div className="pricing-buttons"><button type="button" className="secondary" aria-pressed={!line.pricingProfileOverride} onClick={()=>editLine(line.id,{pricingProfileOverride:null})}>Invoice default</button><button type="button" className="secondary" aria-pressed={line.pricingProfileOverride==='standard'} onClick={()=>editLine(line.id,{pricingProfileOverride:'standard'})}>Standard</button><button type="button" className="secondary" aria-pressed={line.pricingProfileOverride==='legacy'} onClick={()=>editLine(line.id,{pricingProfileOverride:'legacy'})}>Legacy</button></div></div></div>)}</div>
  <div className="invoice-fields tax-fields"><label>Tax treatment<select value={invoice.taxTreatment} onChange={event=>{const taxTreatment=event.target.value as InvoiceDraft['taxTreatment'];editInvoice({taxTreatment,taxRateBps:taxTreatment==='taxable'?invoice.taxRateBps:0});}}><option value="review">Needs review</option><option value="taxable">Taxable</option><option value="no-tax">No tax</option></select></label>{invoice.taxTreatment==='taxable'&&<label>Tax rate (%)<input type="number" min="0" max="100" step="0.01" value={(invoice.taxRateBps/100).toFixed(2)} onChange={event=>editInvoice({taxRateBps:Math.round(Number(event.target.value)*100)})}/></label>}<label className="wide-field">Tax decision note<input value={invoice.taxNote} maxLength={500} placeholder="Record why this treatment applies" onChange={event=>editInvoice({taxNote:event.target.value})}/></label></div>
  <label className="notes-field">Private invoice notes<textarea value={invoice.notes} maxLength={2000} onChange={event=>editInvoice({notes:event.target.value})}/></label>
  <dl className="invoice-totals"><div><dt>Subtotal</dt><dd>{money(amount.subtotal,invoice.currency)}</dd></div><div><dt>Tax</dt><dd>{money(amount.tax,invoice.currency)}</dd></div><div><dt>Total</dt><dd>{money(amount.total,invoice.currency)}</dd></div></dl>
  <label className="status-field">Draft state<select value={invoice.status} onChange={event=>editInvoice({status:event.target.value as InvoiceDraft['status']})}><option value="draft">Keep as draft</option><option value="ready">Ready for issuance review</option></select></label>
  <p className="caption">Ready drafts still stay inside JFM Hub. This action cannot send an invoice, assign an invoice number or update a payment.</p><button className="primary wide" disabled={busy} onClick={onSave}>{busy?'Saving…':'Save invoice draft'}</button>
 </div>;
}
function App(){
 const [session,setSession]=useState<{signedIn:boolean;local:boolean;googleConfigured:boolean}|null>(null),[data,setData]=useState<Data|null>(null),[view,setView]=useState<View>('Overview'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const [query,setQuery]=useState(''),[status,setStatus]=useState('All jobs'),[sort,setSort]=useState('Newest first'),[reviewFilter,setReviewFilter]=useState('Open'),[reviewKind,setReviewKind]=useState('All types');
 const [selected,setSelected]=useState<{job?:Job;review?:Review;invoice?:InvoiceDraft}|null>(null),[note,setNote]=useState(''),[history,setHistory]=useState<any[]|null>(null);
 const dialog=useRef<HTMLDivElement>(null),opener=useRef<HTMLElement|null>(null);
 const refresh=async()=>{try{setData(await api('dashboard'));setError('');}catch(e){if((e as Error&{status?:number}).status===401){setData(null);setSelected(null);setSession(s=>s?{...s,signedIn:false}:s);}setError((e as Error).message);}};
 useEffect(()=>{api('session').then(s=>{setSession(s);if(s.signedIn)refresh();}).catch(()=>setError('The Hub could not connect. Try reloading.'));const t=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(t);},[]);
 useEffect(()=>{if(!selected)return;opener.current=document.activeElement as HTMLElement;setTimeout(()=>dialog.current?.querySelector<HTMLButtonElement>('button')?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,a[href],select')||[]);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);opener.current?.focus();};},[selected]);
 useEffect(()=>{if(!session?.signedIn)return;const t=setInterval(refresh,60000);return()=>clearInterval(t);},[session?.signedIn]);
 const select=(s:{job?:Job;review?:Review;invoice?:InvoiceDraft})=>{setSelected(s.invoice?{...s,invoice:structuredClone(s.invoice)}:s);setNote('');setHistory(null);};
 const editInvoice=(changes:Partial<InvoiceDraft>)=>setSelected(current=>current?.invoice?{...current,invoice:{...current.invoice,...changes}}:current);
 const editLine=(id:string,changes:Partial<InvoiceLine>)=>setSelected(current=>current?.invoice?{...current,invoice:{...current.invoice,lines:current.invoice.lines.map(line=>line.id===id?{...line,...changes}:line)}}:current);
 const action=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');try{await fn();await refresh();setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const nav=(next:View)=>{setView(next);setSelected(null);setQuery('');};
 if(!session)return <main className="loading"><div className="wordmark">JFM</div><h1>Opening your studio.</h1>{error?<p role="alert">{error}</p>:<div className="skeleton"/>}</main>;
 if(!session.signedIn)return <main className="login"><div className="wordmark">JFM</div><p>Jonathan Folk Media</p><h1>Your studio,<br/>in view.</h1><p>Shoots, deadlines and the things that need your attention.</p>{session.googleConfigured?<a className="button primary" href="/auth/start">Sign in with Google</a>:<p>Private sign-in is not configured yet. Complete the setup before using this server.</p>}<small>Private workspace</small></main>;
 if(!data)return <main className="loading"><h1>Loading your desk.</h1>{error&&<><p role="alert">{error}</p><button onClick={refresh}>Try again</button></>}</main>;
 const today=day(new Date(now).toISOString());const open=data.reviews.filter(r=>r.status==='open');
 const upcoming=data.jobs.filter(j=>j.start&&day(j.start)>=today&&!['Cancelled','Held','To reschedule'].includes(j.status)).sort((a,b)=>a.start.localeCompare(b.start));
 const soon=upcoming.filter(j=>Date.parse(j.start)<now+7*86400000);const todays=upcoming.filter(j=>day(j.start)===today);const held=data.jobs.filter(j=>['Held','To reschedule'].includes(j.status));
 const cal=data.connections.find(s=>s.id===(data.mode==='snapshot'?'calendar-export':'google-calendar'));
 const filtered=data.jobs.filter(j=>(status==='All jobs'||j.status===status)&&`${j.client} ${j.title} ${j.location} ${j.services.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='Client name'?a.client.localeCompare(b.client):sort==='Soonest first'?a.start.localeCompare(b.start):b.start.localeCompare(a.start));
 const reviews=data.reviews.filter(r=>{const job=data.jobs.find(item=>item.id===r.jobId);return (reviewFilter==='All'||r.status===reviewFilter.toLowerCase())&&(reviewKind==='All types'||r.kind===reviewKind)&&`${r.title} ${r.detail} ${job?.services.join(' ')||''} ${orderedItems(job).short} ${shortCalendarName(job?.source||r.source,data.connections)}`.toLowerCase().includes(query.toLowerCase());});
 const invoices=data.invoices.filter(invoice=>`${invoice.client} ${invoice.property}`.toLowerCase().includes(query.toLowerCase()));
 const priority=[...open].sort((a,b)=>Number(b.kind==='Possible missed invoice')-Number(a.kind==='Possible missed invoice'));
 const reviewRow=(r:Review,detailed=false)=>{const job=data.jobs.find(j=>j.id===r.jobId),items=orderedItems(job),calendar=shortCalendarName(job?.source||r.source,data.connections);return <button className={'review-row'+(detailed?' review-table-row':'')} key={r.id} aria-label={detailed?`${r.title}, ${r.kind}. Ordered: ${items.full}. Calendar: ${calendar}. ${r.status}.`:undefined} onClick={()=>select({review:r,job})}><span className={'square '+(r.status==='open'?'filled':'')}/><span className="review-subject"><strong>{r.title}</strong><small>{r.kind}</small></span>{detailed&&<><span className="review-ordered" title={items.full}><span className="mobile-label">Ordered: </span>{items.short}</span><span className="review-calendar" title={data.connections.find(connection=>connection.id===(job?.source||r.source))?.label||job?.source||r.source}><span className="mobile-label">Calendar: </span>{calendar}</span></>}<span className="row-end">{r.status==='open'?'Review':r.status==='reviewed'?'Reviewed':'Dismissed'}<span aria-hidden="true">↗</span></span></button>;};
 const invoiceRow=(invoice:InvoiceDraft)=>{const amount=totals(invoice);return <button className="review-row" key={invoice.id} onClick={()=>select({invoice,job:data.jobs.find(job=>job.id===invoice.jobId)})}><span className={'square '+(invoice.status==='ready'?'filled':'')}/><span><strong>{invoice.client}</strong><small>{invoice.property||'Property to confirm'}</small></span><span className="row-end">{money(amount.total,invoice.currency)} · {invoice.status==='ready'?'Ready':'Draft'}<span aria-hidden="true">↗</span></span></button>;};
 const agenda=(jobs:Job[])=>jobs.length?<div className="agenda">{jobs.slice(0,7).map(j=><button key={j.id} className="agenda-row" onClick={()=>select({job:j})}><span className="agenda-date"><b>{date(j.start,{day:'numeric'})}</b><small>{date(j.start,{weekday:'short'})}</small></span><span><strong>{j.client}</strong><small>{j.services.join(', ')}</small><small className="mono">{date(j.start,{hour:'numeric',minute:'2-digit'})}</small></span></button>)}</div>:<div className="empty"><p>No shoots in this window.</p><small>{data.mode==='snapshot'?'This export may not include recent bookings.':'New bookings will appear after a successful sync.'}</small></div>;
 return <div className="app-shell">
  <aside inert={!!selected} className="rail" aria-label="Main navigation"><a href="#" className="wordmark" onClick={e=>{e.preventDefault();nav('Overview');}}>JFM<span>Jonathan Folk Media</span></a><nav>{(['Overview','Jobs','Review','Invoices','Rates','Recently Deleted','Connections'] as View[]).map(v=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>nav(v)}><Icon name={v}/><span>{v}</span>{v==='Review'&&open.length>0&&<small className="nav-count">{open.length}</small>}</button>)}</nav><div className="rail-bottom"><div className="fresh"><span className={'square '+(data.mode==='live'&&!cal?.error?'filled':'')}/>{data.mode==='snapshot'?'Using an export':cal?.error?'Connection needs you':'Calendar connected'}</div><small>{data.mode==='snapshot'?'Captured 19 Sep 2026':`Last success ${age(cal?.lastSuccess||null,now)}`}</small><p className="rail-name">Jonathan Folk</p><small>{session.local?'On this Mac':'Private workspace'}</small></div></aside>
  <div inert={!!selected} className="workspace">
   <header className="topbar"><span>{view}</span><span className="mono">{date(new Date(now).toISOString(),{weekday:'short',day:'numeric',month:'short',year:'numeric'})}</span><button className="text-button" onClick={()=>nav('Connections')}><span className="square"/>{data.mode==='snapshot'?'Export snapshot':cal?.error?'Sync failed':age(cal?.lastSuccess||null,now)}</button></header>
   <main id="main-content">
    {error&&<div className="message error" role="alert"><strong>Needs attention</strong><span>{error}</span><button className="text-button" onClick={()=>setError('')}>Dismiss</button></div>}
    {notice&&<div className="message" role="status"><span>{notice}</span><button className="text-button" onClick={()=>setNotice('')}>Dismiss</button></div>}
    {view==='Overview'&&<>
     <div className="page-heading"><div><p className="eyebrow">Your working day</p><h1>On your desk.</h1><p className="lead">{todays.length?`${todays.length} shoot${todays.length===1?'':'s'} today.`:'A little room to look ahead.'} <span>{open.length} items are waiting for a look.</span></p></div><button className="primary" onClick={()=>nav('Review')}>Review your queue <span className="button-count">{open.length}</span></button></div>
     {data.mode==='snapshot'&&<div className="snapshot-note"><span className="square"/><p><strong>A reference snapshot.</strong> Calendar and invoice evidence from 19 September. New changes will appear after you connect the live calendar.</p><button className="text-button" onClick={()=>nav('Connections')}>Connections</button></div>}
     <div className="overview-grid"><div className="overview-main">
      <section className="attention-panel"><div className="section-heading"><div><h2>Needs your attention</h2><p className="caption">A few things to review before moving on.</p></div><button className="text-button" onClick={()=>nav('Review')}>View all {open.length}</button></div>{priority.length?priority.slice(0,4).map(review=>reviewRow(review)):<div className="empty">Your review queue is clear.</div>}</section>
      <section className="metrics"><div><small>Coming up in 7 days</small><p className="metric-value">{soon.length}</p><span>scheduled shoots</span></div><div><small>Possible missed invoices</small><p className="metric-value">{open.filter(r=>r.kind==='Possible missed invoice').length}</p><span>evidence to review</span></div><div><small>Invoice drafts</small><p className="metric-value">{data.invoices.length}</p><span>{data.invoices.filter(invoice=>invoice.status==='ready').length} ready for the next step</span></div><div><small>Waiting on a date</small><p className="metric-value">{held.length}</p><span>held or to reschedule</span></div></section>

     </div><section className="upcoming-section"><div className="section-heading"><h2>Next up</h2><span className="mono small">{upcoming.length}</span></div>{agenda(upcoming)}<button className="secondary wide" onClick={()=>{nav('Jobs');setSort('Soonest first');}}>Open the job list</button></section></div>
    </>}
    {view==='Jobs'&&<>
     <div className="page-heading"><div><p className="eyebrow">The shooting schedule</p><h1>Every job, in view.</h1><p className="lead">{data.jobs.length} bookings from your {data.mode==='snapshot'?'calendar export':'connected calendar'}.</p></div><span className="stamp">Read-only calendar</span></div>
     <div className="toolbar"><label className="search">Search jobs<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Client, property or service" type="search"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['All jobs','Booked','Held','To reschedule','Cancelled','Needs review'].map(v=><option key={v}>{v}</option>)}</select></label><label>Order<select value={sort} onChange={e=>setSort(e.target.value)}>{['Newest first','Soonest first','Client name'].map(v=><option key={v}>{v}</option>)}</select></label><span className="results">{filtered.length} jobs</span></div>
     <div className="job-table" role="table" aria-label="Jobs"><div className="table-head" role="row"><span role="columnheader">Shoot</span><span role="columnheader">Client & property</span><span role="columnheader">Services</span><span role="columnheader">Suggested due</span><span role="columnheader">Status</span></div>{filtered.map(j=><button role="row" className="job-row" key={j.id} onClick={()=>select({job:j})}><span role="cell" className="mono job-date">{date(j.start)}<small>{date(j.start,{hour:'numeric',minute:'2-digit'})}</small></span><span role="cell" className="job-client"><strong>{j.client||'Client needs review'}</strong><small>{j.location||'Property to confirm'}</small></span><span role="cell" className="job-services">{j.services.join(', ')}</span><span role="cell" className="mono job-due">{j.due?date(j.due):'Confirm'}{j.due&&<small>Provisional</small>}</span><span role="cell" className="job-state"><span className={'status '+(j.status==='Cancelled'?'muted':j.status==='Booked'?'':'outlined')}>{j.status}</span></span></button>)}</div>{!filtered.length&&<div className="empty"><h2>No matching jobs.</h2><p>Try a different name or clear the filters.</p><button onClick={()=>{setQuery('');setStatus('All jobs');}}>Clear filters</button></div>}
    </>}
    {view==='Review'&&<>
     <div className="page-heading"><div><p className="eyebrow">A human check, before the next step</p><h1>Needs a closer look.</h1><p className="lead">Review evidence and add a note when useful. Source invoices and payments stay unchanged.</p></div><span className="stamp">{open.length} open</span></div>
     <div className="toolbar"><label className="search">Search the queue<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Client or issue"/></label><label>Show<select value={reviewFilter} onChange={e=>setReviewFilter(e.target.value)}>{['Open','Reviewed','Dismissed','All'].map(x=><option key={x}>{x}</option>)}</select></label><label>Type<select value={reviewKind} onChange={e=>setReviewKind(e.target.value)}>{['All types',...new Set(data.reviews.map(r=>r.kind))].map(x=><option key={x}>{x}</option>)}</select></label></div>
     <section className="review-table">{reviews.length?<><div className="review-table-head" aria-hidden="true"><span/><span>Item</span><span>Ordered</span><span>Calendar</span><span>Status</span></div>{reviews.map(review=>reviewRow(review,true))}</>:<div className="empty"><h2>Nothing in this view.</h2><p>Try another filter, or return to your jobs.</p></div>}</section>
    </>}
    {view==='Invoices'&&<>
     <div className="page-heading"><div><p className="eyebrow">Phase 2 · private drafting</p><h1>Invoices, before they leave.</h1><p className="lead">Confirm the completed work, pricing and tax treatment. Drafts stay inside the Hub and do not change the master Sheet.</p></div><span className="stamp">{data.invoices.filter(invoice=>invoice.status==='ready').length} ready</span></div>
     <div className="toolbar"><label className="search">Search invoice drafts<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Client or property"/></label><span className="results">{invoices.length} drafts</span></div>
     <section>{invoices.length?invoices.map(invoiceRow):<div className="empty"><h2>No invoice drafts yet.</h2><p>Open a booked job and choose Start invoice draft. Nothing will be sent.</p><button onClick={()=>nav('Jobs')}>Open jobs</button></div>}</section>
     <div className="phase-boundary"><strong>Issuance is deliberately off.</strong><p>Ready means reviewed inside JFM Hub. Invoice numbering, master-Sheet writes, PDF delivery and payment changes are not connected yet.</p></div>
    </>}
    {view==='Rates'&&<RateCatalog rates={data.rates} busy={busy} onSave={rate=>action(()=>api('rates',rate),'Rate saved to the private catalog.')}/>}
    {view==='Recently Deleted'&&<><div className="page-heading"><div><p className="eyebrow">Recoverable Hub items</p><h1>Recently Deleted.</h1><p className="lead">These shoots and their linked Hub records are hidden from active views. Restore a shoot to return it to the Hub.</p></div><span className="stamp">{data.deletedItems.length} items</span></div><section className="deleted-list">{data.deletedItems.length?data.deletedItems.map(item=><div className="deleted-row" key={item.reviewId}><span><strong>{item.title}</strong><small>Moved here {date(item.deletedAt,{day:'numeric',month:'short',year:'numeric'})}</small></span><button className="secondary" disabled={busy} onClick={()=>action(()=>api(`deleted/${item.reviewId}/restore`,{}),'Shoot restored to the Hub.')}>Restore</button></div>):<div className="empty"><h2>The bin is empty.</h2><p>Deleted shoots can be restored here.</p></div>}</section></>}
    {view==='Connections'&&<>
     <div className="page-heading"><div><p className="eyebrow">Know where things stand</p><h1>Freshness, at a glance.</h1><p className="lead">A failed attempt never replaces the last successful sync.</p></div><button className="primary" disabled={busy||!data.calendarConnected} onClick={()=>action(()=>api('refresh',{}),'All approved calendars refreshed successfully.')}>{busy?'Working…':'Refresh calendar'}</button></div>
     <section className="connection-list">{data.connections.map(c=><article key={c.id} className="connection"><div><h2>{c.label}</h2><p>{c.mode==='export'?'Imported reference':c.mode==='not-connected'?'Awaiting first successful sync':c.error?'Needs attention':'Background connection'}</p>{c.error&&<p className="error-text">{c.error}</p>}</div><dl><div><dt>Last successful sync</dt><dd>{age(c.lastSuccess,now)}</dd></div><div><dt>{c.mode==='export'?'Snapshot date':'Last attempt'}</dt><dd>{c.mode==='export'?(c.snapshotAt?date(c.snapshotAt,{day:'numeric',month:'short',year:'numeric'}):'Unknown'):age(c.lastAttempt,now)}</dd></div></dl><span className="status outlined">{c.mode==='export'?'Export only':c.mode==='not-connected'?'Not connected':c.error?'Failed':c.lastSuccess&&now-Date.parse(c.lastSuccess)>(c.id==='backup'?26:2)*3600000?'Delayed':'Current'}</span></article>)}</section>
     <div className="settings-grid"><section><h2>Connect your booking calendar</h2><p>Use jcwfolk@gmail.com. The Hub requests read-only Calendar access. Your business account signs in separately.</p>{data.googleConfigured?<a className="button secondary" href="/auth/start?kind=calendar">{data.calendarConnected?'Reconnect Google Calendar':'Connect Google Calendar'}</a>:<div className="setup-note"><strong>Google setup is pending</strong><p>The app needs its own Google credentials and approved redirect address. Connecting the Codex plugin does not connect this app.</p></div>}<p className="caption">Approved calendars are checked hourly, with a daily full reconciliation. Subcontractor bookings require For J. No AI calls.</p></section><section><h2>Connect commercial quote email</h2><p>Connect info@jonathanfolk.ca with read-only Gmail access to suggest quoted prices on commercial invoice drafts.</p>{data.googleConfigured?<a className="button secondary" href="/auth/start?kind=gmail">{data.gmailConnected?'Reconnect Gmail':'Connect Gmail'}</a>:<p className="caption">Google setup is required first.</p>}<p className="caption">Only matching messages are searched when a commercial draft opens. Email content is not stored in the Hub.</p></section><section><h2>Keep a recovery copy</h2><p>{data.secondaryBackupConfigured?'Daily and monthly copies are written locally and to the configured independent recovery target.':'Local daily and monthly copies are enabled. An independent Canadian recovery target is still required.'}</p><button className="secondary" disabled={busy} onClick={()=>action(()=>api('backup',{}),'Recovery copies saved and checked.')}>Create and verify backups</button><p className="caption">Latest successful backup: {age(data.lastBackup,now)}.</p></section></div>
     <section className="privacy-note">{!session.local&&<button className="secondary" onClick={()=>action(async()=>{const r=await fetch('/auth/logout',{method:'POST',headers:{'X-JFM-Request':'1'}});if(!r.ok)throw new Error('Sign-out could not finish.');setData(null);setSelected(null);setSession({...session,signedIn:false});},'Signed out.')}>Sign out</button>}<h2>Your data stays under your control.</h2><p>Canadian hosting required. External AI, invoice sending, automatic payment changes and calendar edits are disabled in this phase.</p><p className="caption">Independent outage alerts, residency and recovery restores require production verification.</p></section>
    </>}
    <footer><span>Jonathan Folk Media</span><span>Phase 2 / Controlled invoice drafting</span></footer>
   </main>
  </div>
  {selected&&<>
   <div className="scrim" onClick={()=>setSelected(null)}/>
   <div ref={dialog} className="detail" role="dialog" aria-modal="true" aria-labelledby="detail-title">
    <div className="detail-top"><span>{selected.invoice?'Invoice draft':selected.review?'Review item':'Job detail'}</span><button aria-label="Close details" onClick={()=>setSelected(null)}>×</button></div>
    <div className="detail-body"><p className="eyebrow">{selected.invoice?selected.invoice.status:selected.review?.kind||selected.job?.status}</p><h2 id="detail-title">{selected.invoice?.client||selected.review?.title||selected.job?.client}</h2>
     {selected.review&&<><p>{selected.review.detail}</p><p className="caption">Source: {selected.review.source}</p>{selected.review.status!=='open'&&<div className="setup-note"><strong>{selected.review.status==='reviewed'?'Reviewed':'Dismissed'}</strong>{selected.review.resolution&&<p>{selected.review.resolution}</p>}</div>}</>}
     {selected.job&&!selected.invoice&&<><dl className="job-facts"><div><dt>Calendar</dt><dd>{data.connections.find(c=>c.id===selected.job!.source)?.label||selected.job.source}</dd></div><div><dt>Shoot</dt><dd>{date(selected.job.start,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}<br/>{date(selected.job.start,{hour:'numeric',minute:'2-digit'})}</dd></div><div><dt>Property</dt><dd>{selected.job.location||'Needs confirmation'}</dd></div><div><dt>Services</dt><dd>{selected.job.services.join(', ')}</dd></div><div><dt>Suggested files due</dt><dd>{selected.job.due?date(selected.job.due,{weekday:'long',day:'numeric',month:'short'}):'Needs confirmation'}<small>{selected.job.deadlineBasis}</small></dd></div><div><dt>Calendar title</dt><dd>{selected.job.title}</dd></div></dl>{selected.job.notes.length>0&&<p className="caption">Notes: {selected.job.notes.join(', ')}</p>}{selected.job.issues.length>0&&<div className="detail-checks"><h3>Before invoicing</h3><ul>{selected.job.issues.map(i=><li key={i}>{i}</li>)}</ul></div>}{!selected.review&&<div className="invoice-start">{data.invoices.find(invoice=>invoice.jobId===selected.job!.id)?<button className="primary" onClick={()=>select({invoice:data.invoices.find(invoice=>invoice.jobId===selected.job!.id)!,job:selected.job})}>Open invoice draft</button>:<button className="primary" disabled={busy||selected.job.status!=='Booked'} onClick={()=>action(async()=>{const invoice=await api('invoices',{jobId:selected.job!.id});setView('Invoices');select({invoice,job:selected.job});},'Invoice draft created. Nothing was sent.')}>Start invoice draft</button>}<p className="caption">Drafting creates a private Hub record only. It does not issue an invoice or update Google Sheets.</p></div>}<button className="text-button" onClick={async()=>{try{setHistory(await api(`jobs/${selected.job!.id}/history`));}catch(e){setError((e as Error).message);}}}>View source history</button>{history&&<div className="history">{history.length?history.map((h,i)=><p key={i}><small>{date(h.at,{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}</small>{h.job.title}<br/>{date(h.job.start)} / {h.job.status}</p>):<p>No earlier version is recorded.</p>}</div>}</>}
     {selected.job&&!selected.review&&!selected.invoice&&<div className="delete-action"><button className="secondary" disabled={busy} onClick={()=>action(async()=>{await api(`jobs/${selected.job!.id}/delete`,{});setSelected(null);},'Shoot moved to Recently Deleted.')}>Delete to Recently Deleted</button><p className="caption">Hides this shoot and its linked Hub records. Restore it from the left navigation.</p></div>}
     {selected.invoice&&<><InvoiceSuggestions invoice={selected.invoice} category={data.sorts.find(sort=>sort.jobId===selected.invoice?.jobId)?.category} gmailConnected={data.gmailConnected} editLine={editLine} editInvoice={editInvoice} onAutomaticProfile={profile=>setSelected(current=>current?.invoice&&current.invoice.pricingProfileMode==='automatic'&&current.invoice.pricingProfile!==profile?{...current,invoice:{...current.invoice,pricingProfile:profile}}:current)}/><InvoiceEditor invoice={selected.invoice} busy={busy} editInvoice={editInvoice} editLine={editLine} onSave={()=>action(async()=>{await api(`invoices/${selected.invoice!.id}`,{expectedUpdatedAt:selected.invoice!.updatedAt,draft:selected.invoice});setSelected(null);},selected.invoice!.status==='ready'?'Invoice draft marked ready. Nothing was sent.':'Invoice draft saved. Nothing was sent.')}/></>}
     {selected.review&&selected.review.status==='open'&&<ReviewSorter key={selected.review.id} note={note} onNote={setNote} busy={busy} onSort={(category:ShootCategory,squareFootageRange:string)=>action(async()=>{await api(`reviews/${selected.review!.id}/sort`,{category,squareFootageRange,resolution:note});setSelected(null);},`${category} shoot sorted. Invoice draft is available for booked jobs.`)} onDelete={()=>action(async()=>{await api(`reviews/${selected.review!.id}/delete`,{});setSelected(null);},'Shoot moved to Recently Deleted.')}/>}
    </div>
   </div>
  </>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
