import React,{useEffect,useState} from 'react';
import {shootCategories,squareFootageRanges} from '../server/types';
import type {CustomPricePrompt,EmailPriceSuggestion,InvoiceDraft,InvoiceLine,InvoiceReference,PriceSuggestion,PricingProfile,Rate,ShootCategory} from '../server/types';

async function request(path:string,body?:unknown){const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-JFM-Request':'1'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}
const money=(cents:number,currency:'CAD'|'USD')=>new Intl.NumberFormat('en-CA',{style:'currency',currency}).format(cents/100);

export function ReviewSorter({note,onNote,busy,onSort,onDelete}:{note:string;onNote:(value:string)=>void;busy:boolean;onSort:(category:ShootCategory,range:string)=>void;onDelete:()=>void}){
 const [range,setRange]=useState('');
 return <div className="review-form"><label htmlFor="review-note">Review note <span className="caption">(optional)</span></label><textarea id="review-note" value={note} onChange={event=>onNote(event.target.value)} maxLength={1000} placeholder="Add context if it will be useful later"/>
  <h3>Sort this shoot</h3><p className="caption">Choose its type to move it toward invoice drafting.</p>
  <div className="sort-actions"><div className="real-estate-sort"><label htmlFor="sort-range">Real Estate square footage</label><select id="sort-range" value={range} onChange={event=>setRange(event.target.value)}><option value="">Choose a range</option>{squareFootageRanges.map(value=><option key={value}>{value}</option>)}</select><button className="primary" disabled={busy||!range} onClick={()=>onSort('Real Estate',range)}>Real Estate</button></div>
   {shootCategories.filter(category=>category!=='Real Estate').map(category=><button className="secondary" key={category} disabled={busy} onClick={()=>onSort(category,'')}>{category}</button>)}
  </div>
  <div className="delete-action"><button className="secondary" disabled={busy} onClick={onDelete}>Delete to Recently Deleted</button><p className="caption">Hides the entire shoot and its linked Hub records. You can restore it from the left navigation.</p></div>
 </div>;
}

export function RateCatalog({rates,busy,onSave}:{rates:Rate[];busy:boolean;onSave:(rate:Pick<Rate,'profile'|'category'|'service'|'squareFootageRange'|'currency'|'unitPriceCents'>)=>void}){
 const [category,setCategory]=useState<ShootCategory>('Real Estate'),[service,setService]=useState(''),[range,setRange]=useState(''),[currency,setCurrency]=useState<'CAD'|'USD'>('CAD'),[amount,setAmount]=useState('');
 const [profile,setProfile]=useState<PricingProfile>('standard'),[filter,setFilter]=useState('All'),[questions,setQuestions]=useState<any[]>([]),[imports,setImports]=useState<any[]>([]);
 useEffect(()=>{request('reference/pricing-questions').then(result=>{setQuestions(result.questions);setImports(result.imports);}).catch(()=>{});},[]);
 const canSave=service.trim().length>=2&&(category!=='Real Estate'||!!range)&&/^\d+(?:\.\d{1,2})?$/.test(amount)&&Number(amount)>0;
 return <><div className="page-heading"><div><p className="eyebrow">Private pricing reference</p><h1>Rates.</h1><p className="lead">Approved rates appear as suggestions on matching invoice lines. You choose whether to apply them.</p></div><span className="stamp">{rates.length} rates</span></div>
  <section className="rate-panel"><h2>Add a rate</h2><div className="rate-fields"><label>Pricing profile<select value={profile} onChange={event=>setProfile(event.target.value as PricingProfile)}><option value="standard">Standard</option><option value="legacy">Legacy</option></select></label><label>Type<select value={category} onChange={event=>{setCategory(event.target.value as ShootCategory);setRange('');}}>{shootCategories.map(value=><option key={value}>{value}</option>)}</select></label><label>Service<input value={service} maxLength={160} placeholder="Match an invoice line, e.g. Premium photo" onChange={event=>setService(event.target.value)}/></label>{category==='Real Estate'&&<label>Square footage<select value={range} onChange={event=>setRange(event.target.value)}><option value="">Choose a range</option>{squareFootageRanges.map(value=><option key={value}>{value}</option>)}</select></label>}<label>Currency<select value={currency} onChange={event=>setCurrency(event.target.value as 'CAD'|'USD')}><option>CAD</option><option>USD</option></select></label><label>Rate<input type="number" min="0.01" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)}/></label></div><button className="primary" disabled={busy||!canSave} onClick={()=>{onSave({profile,category,service:service.trim(),squareFootageRange:category==='Real Estate'?range:'',currency,unitPriceCents:Math.round(Number(amount)*100)});setAmount('');}}>Save rate</button></section>
  <section className="rate-panel"><div className="section-heading"><h2>Rate catalog</h2><div className="rate-filters"><label>Profile<select value={profile} onChange={event=>setProfile(event.target.value as PricingProfile)}><option value="standard">Standard</option><option value="legacy">Legacy</option></select></label><label>Show<select value={filter} onChange={event=>setFilter(event.target.value)}><option>All</option>{shootCategories.map(value=><option key={value}>{value}</option>)}</select></label></div></div>{rates.length?rates.filter(rate=>rate.profile===profile&&(filter==='All'||rate.category===filter)).map(rate=><div className="rate-row" key={rate.id}><span><strong>{rate.service}</strong><small>{rate.category}{rate.squareFootageRange?` · ${rate.squareFootageRange}`:''} · {rate.source}</small>{rate.note&&<small>{rate.note}</small>}</span><span>{money(rate.unitPriceCents,rate.currency)}{rate.unit!=='job'?`/${rate.unit}`:''}</span></div>):<p className="caption">No rates are stored yet. Import the approved rate sheet or add a rate above.</p>}</section>
  <section className="rate-panel"><h2>Pricing decisions</h2><p className="caption">{imports.length?'Imported observed prices are evidence only. They do not change Standard or Legacy sheet rates.':'No historical pricing dataset has been imported into this Hub database yet.'}</p>{questions.length>0&&<details><summary>{questions.length} source rows flagged for confirmation</summary><div className="pricing-questions">{questions.map((item,index)=><div className="rate-row" key={index}><span><strong>{item.item}</strong><small>{item.table} · {item.source}</small><small>{item.condition}</small><small>{item.note}</small></span><span>{item.priceCad?`CAD $${item.priceCad}`:'Custom'}</span></div>)}</div></details>}</section>
 </>;
}

export function InvoiceSuggestions({invoice,category,gmailConnected,editLine,editInvoice,onAutomaticProfile}:{invoice:InvoiceDraft;category:ShootCategory|undefined;gmailConnected:boolean;editLine:(id:string,changes:Partial<InvoiceLine>)=>void;editInvoice:(changes:Partial<InvoiceDraft>)=>void;onAutomaticProfile:(profile:InvoiceDraft['pricingProfile'])=>void}){
 const [rates,setRates]=useState<PriceSuggestion[]>([]),[custom,setCustom]=useState<CustomPricePrompt[]>([]),[emails,setEmails]=useState<EmailPriceSuggestion[]>([]),[reference,setReference]=useState<InvoiceReference|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[emailLoading,setEmailLoading]=useState(false),[targetLine,setTargetLine]=useState(invoice.lines[0]?.id||'');
 useEffect(()=>{setReference(null);let active=true;const timer=setTimeout(()=>request(`invoices/${invoice.id}/reference?client=${encodeURIComponent(invoice.client)}`).then((result:InvoiceReference)=>{if(active){setReference(result);if(invoice.pricingProfileMode==='automatic')onAutomaticProfile(result.automatic.profile);}}).catch(error=>{if(active)setError(error.message);}),250);return()=>{active=false;clearTimeout(timer);};},[invoice.id,invoice.client,invoice.pricingProfileMode]);
 useEffect(()=>{setRates([]);setCustom([]);setError('');let active=true;const timer=setTimeout(()=>{setLoading(true);request(`invoices/${invoice.id}/suggestions`,{draft:invoice}).then(result=>{if(active){setRates(result.rates);setCustom(result.custom);if(invoice.pricingProfileMode==='automatic')onAutomaticProfile(result.profile);}}).catch(error=>{if(active)setError(error.message);}).finally(()=>{if(active)setLoading(false);});},200);return()=>{active=false;clearTimeout(timer);};},[JSON.stringify(invoice),category]);
 const setClientProfile=async(profile:PricingProfile|null)=>{try{setError('');const result:InvoiceReference=await request(`invoices/${invoice.id}/client-pricing`,{client:invoice.client,profile});setReference(result);if(invoice.pricingProfileMode==='automatic')onAutomaticProfile(result.automatic.profile);}catch(error){setError((error as Error).message);}};
 const applyMatching=()=>editInvoice({lines:invoice.lines.map(line=>{const suggestion=rates.find(item=>item.lineId===line.id);return suggestion?{...line,unitPriceCents:suggestion.amountCents}:line;})});
 useEffect(()=>{setEmails([]);let active=true;if(category==='Commercial'&&gmailConnected){setEmailLoading(true);request(`invoices/${invoice.id}/email-prices`).then(result=>{if(active)setEmails(result);}).catch(error=>{if(active)setError(error.message);}).finally(()=>{if(active)setEmailLoading(false);});}return()=>{active=false;};},[invoice.id,category,gmailConnected]);
 return <section className="invoice-suggestions"><h3>Customer pricing evidence</h3>{reference?<><p className="caption">{reference.warning} {reference.automatic.reason}</p>{reference.customer&&<p><strong>{reference.customer.displayName}</strong> · imported status: {reference.customer.legacyStatus} · {reference.customer.pdfInvoices2026} PDF invoices in 2026</p>}{reference.customer&&reference.customer.profileHint!=='review'&&invoice.pricingProfile!=='review'&&reference.customer.profileHint!==invoice.pricingProfile&&<p className="custom-price">Selected {invoice.pricingProfile} pricing differs from the imported {reference.customer.profileHint} hint. Check the customer identity and agreement before saving.</p>}<div className="pricing-buttons"><span className="caption">This and future automatic drafts for this billing client:</span><button className="secondary" type="button" disabled={!reference.automatic.canSetClientOverride} aria-pressed={reference.automatic.clientOverride==='standard'} onClick={()=>setClientProfile('standard')}>Use Standard for client</button><button className="secondary" type="button" disabled={!reference.automatic.canSetClientOverride} aria-pressed={reference.automatic.clientOverride==='legacy'} onClick={()=>setClientProfile('legacy')}>Use Legacy for client</button>{reference.automatic.clientOverride&&<button className="secondary" type="button" onClick={()=>setClientProfile(null)}>Clear client override</button>}</div>{reference.historicalInvoices.length>0&&<details><summary>{reference.historicalInvoices.length} matching historical PDF invoices</summary><div className="pricing-questions">{reference.historicalInvoices.map((item,index)=><div className="rate-row" key={`${item.file}-${index}`}><span><strong>{item.number||item.file}</strong><small>{item.issued} · {item.services}</small>{!item.reconciles&&<small>Printed total did not reconcile in source extraction</small>}</span><span>{item.balance}</span></div>)}</div></details>}</>:<p className="caption">Checking imported customer history…</p>}
  <h3>Price suggestions</h3><p className="caption">Suggestions are evidence to review. Nothing is added to the invoice until you apply a price and save the draft.</p>
  {loading?<p className="caption">Checking approved rates…</p>:rates.length?<><button className="secondary" type="button" onClick={applyMatching}>Apply all {rates.length} matching sheet prices</button><p className="caption">This replaces current amounts only on matching lines. Custom quotes and unmatched lines are left unchanged.</p>{rates.map(suggestion=><div className="suggestion-row" key={suggestion.lineId}><span>{suggestion.service} · {suggestion.profile}: {money(suggestion.amountCents,suggestion.currency)}</span><button className="secondary" onClick={()=>editLine(suggestion.lineId,{unitPriceCents:suggestion.amountCents})}>Apply to line</button></div>)}</>:custom.length?null:invoice.pricingProfile==='review'&&!invoice.lines.some(line=>line.pricingProfileOverride)?<p className="custom-price">Confirm Standard or Legacy pricing on the invoice or each line to see sheet-rate suggestions.</p>:<p className="caption">No approved rate matches this profile, type, range, service and currency.</p>}
  {custom.map(prompt=><div className="custom-price" key={prompt.lineId}><strong>Custom price needed for {prompt.service}</strong><p>{prompt.note}</p><p className="caption">Enter the confirmed amount on the invoice line below.</p></div>)}
  {category==='Commercial'&&<div className="email-suggestions"><h3>Commercial quotes in Gmail</h3>{!gmailConnected?<p className="caption">Connect info@jonathanfolk.ca in Connections to search for quote emails.</p>:<><p className="caption">Searches recent matching messages when this draft opens. Verify the client and scope of each quote before applying a price.</p>{emailLoading?<p className="caption">Searching Gmail…</p>:emails.length?<><label>Apply to invoice line<select value={targetLine} onChange={event=>setTargetLine(event.target.value)}>{invoice.lines.map(line=><option key={line.id} value={line.id}>{line.description}</option>)}</select></label>{emails.map((suggestion,index)=><div className="email-result" key={`${suggestion.messageId}-${index}`}><strong>{money(suggestion.amountCents,suggestion.currency)} · {suggestion.subject||'Email quote'}</strong><small>{suggestion.from} · {suggestion.date}</small><p>{suggestion.excerpt}</p><div className="actions"><a href={`https://mail.google.com/mail/u/0/#all/${encodeURIComponent(suggestion.threadId)}`} target="_blank" rel="noopener noreferrer">Open email</a><button className="secondary" disabled={!targetLine||suggestion.currency!==invoice.currency} onClick={()=>editLine(targetLine,{unitPriceCents:suggestion.amountCents})}>Apply price</button></div></div>)}</>:<p className="caption">No explicit CAD or USD amounts were found in the matching emails.</p>}</>}</div>}
  {error&&<p className="error-text" role="alert">{error}</p>}
 </section>;
}
