import React,{useEffect,useState} from 'react';
import {shootCategories,squareFootageRanges} from '../server/types';
import type {CustomPricePrompt,EmailPriceSuggestion,InvoiceDraft,InvoiceLine,InvoiceReference,PriceSuggestion,PricingProfile,Rate,ShootCategory,SortDetails} from '../server/types';
import {CommercialFields,TrashIcon} from './WorkflowControls';
import {groupRates} from './rate-groups';

async function request(path:string,body?:unknown){const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-JFM-Request':'1'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}
const money=(cents:number,currency:'CAD'|'USD')=>new Intl.NumberFormat('en-CA',{style:'currency',currency}).format(cents/100);

export function ReviewNote({note,onNote}:{note:string;onNote:(value:string)=>void}){
 return <div className="review-form"><label htmlFor="review-note">Review note <span className="caption">(optional)</span></label><textarea id="review-note" value={note} onChange={event=>onNote(event.target.value)} maxLength={1000} placeholder="Add context if it will be useful later"/></div>;
}

export function ReviewSorter({busy,onSort,onDelete}:{busy:boolean;onSort:(category:ShootCategory,range:string,details:SortDetails,openInvoice:boolean)=>void;onDelete:()=>void}){
 const [range,setRange]=useState(''),[category,setCategory]=useState<ShootCategory>('Real Estate'),[details,setDetails]=useState<SortDetails>({});
 return <section className="review-form shoot-sorter" aria-labelledby="shoot-sort-title">
  <div className="shoot-sort-heading"><h3 id="shoot-sort-title">Sort this shoot</h3><button className="secondary icon-button" disabled={busy} title="Move to Recently Deleted — can be restored" aria-label="Move to Recently Deleted" onClick={onDelete}><TrashIcon/></button></div>
  <div className="category-choices">{shootCategories.map(value=><button key={value} className="secondary" disabled={busy} aria-pressed={category===value} onClick={()=>setCategory(value)}>{value}</button>)}</div>
  {category==='Real Estate'&&<div className="real-estate-sort"><label htmlFor="sort-range">Real Estate package / size</label><select id="sort-range" value={range} onChange={event=>setRange(event.target.value)}><option value="">Choose a package or size</option>{squareFootageRanges.map(value=><option key={value}>{value}</option>)}</select></div>}
  {category==='Commercial'&&<div className="commercial-choice"><CommercialFields details={details} onChange={setDetails}/><small>Choose the commercial rate for this photoshoot. Existing draft lines and prices are preserved.</small></div>}
  <div className="sort-submit">{[false,true].map(openInvoice=><button key={String(openInvoice)} className={openInvoice?'primary':'secondary'} disabled={busy||(category==='Real Estate'&&!range)||(category==='Commercial'&&!details.commercialSubtype)} onClick={()=>onSort(category,category==='Real Estate'?range:'',category==='Commercial'?details:{},openInvoice)}>{openInvoice?'Submit + Invoice':'Submit'}</button>)}</div>
 </section>;
}

function RateGroup({rates}:{rates:Rate[]}){const [id,setId]=useState(rates[0].id);const rate=rates.find(r=>r.id===id)||rates[0];return <div className="rate-row"><span><strong>{rate.service}</strong><small>{rate.category} · {rate.currency} / {rate.unit}</small><small>{rate.source}</small>{rate.note&&<small>{rate.note}</small>}</span><label className="rate-variant-select">Available prices<select aria-label={`Prices for ${rate.service}`} value={rate.id} onChange={e=>setId(e.target.value)}>{rates.map(r=><option key={r.id} value={r.id}>{r.profile==='standard'?'Standard':'Legacy'} · {r.squareFootageRange||'All sizes'} · {money(r.unitPriceCents,r.currency)} / {r.unit}</option>)}</select></label></div>;}
export function RateCatalog({rates,busy,onSave}:{rates:Rate[];busy:boolean;onSave:(rate:Pick<Rate,'profile'|'category'|'service'|'squareFootageRange'|'currency'|'unitPriceCents'|'unit'>)=>void}){
 const [adding,setAdding]=useState(false),[unit,setUnit]=useState<Rate['unit']>('job'),[catalogProfile,setCatalogProfile]=useState('all');
 const [category,setCategory]=useState<ShootCategory>('Real Estate'),[service,setService]=useState(''),[range,setRange]=useState(''),[currency,setCurrency]=useState<'CAD'|'USD'>('CAD'),[amount,setAmount]=useState('');
 const [profile,setProfile]=useState<PricingProfile>('standard'),[filter,setFilter]=useState('All'),[questions,setQuestions]=useState<any[]>([]),[imports,setImports]=useState<any[]>([]);
 useEffect(()=>{request('reference/pricing-questions').then(result=>{setQuestions(result.questions);setImports(result.imports);}).catch(()=>{});},[]);
 const canSave=service.trim().length>=2&&/^\d+(?:\.\d{1,2})?$/.test(amount)&&Number(amount)>0;
 return <><div className="page-heading"><div><p className="eyebrow">Private pricing reference</p><h1>Rates.</h1><p className="lead">Approved rates appear as suggestions on matching invoice lines. You choose whether to apply them.</p></div><button className="primary" onClick={()=>setAdding(!adding)}>{adding?'Close add rate':'+ Add rate'}</button></div>
  {adding&&<section className="rate-panel"><h2>Add a rate</h2><div className="rate-fields"><label>Pricing profile<select value={profile} onChange={event=>setProfile(event.target.value as PricingProfile)}><option value="standard">Standard</option><option value="legacy">Legacy</option></select></label><label>Type<select value={category} onChange={event=>{setCategory(event.target.value as ShootCategory);setRange('');}}>{shootCategories.map(value=><option key={value}>{value}</option>)}</select></label><label>Service<input value={service} maxLength={160} placeholder="Match an invoice line, e.g. Premium photo" onChange={event=>setService(event.target.value)}/></label>{category==='Real Estate'&&<label>Square footage<select value={range} onChange={event=>setRange(event.target.value)}><option value="">All sizes / add-on</option>{squareFootageRanges.map(value=><option key={value}>{value}</option>)}</select></label>}<label>Currency<select value={currency} onChange={event=>setCurrency(event.target.value as 'CAD'|'USD')}><option>CAD</option><option>USD</option></select></label><label>Charge per<select value={unit} onChange={e=>setUnit(e.target.value as Rate['unit'])}><option value="job">Job</option><option value="image">Image</option><option value="service">Service</option><option value="deliverable">Deliverable</option></select></label><label>Rate<input type="number" min="0.01" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)}/></label></div><button className="primary" disabled={busy||!canSave} onClick={()=>{onSave({profile,category,service:service.trim(),squareFootageRange:category==='Real Estate'?range:'',currency,unit,unitPriceCents:Math.round(Number(amount)*100)});setAmount('');}}>Save rate</button></section>}
  <section className="rate-panel"><div className="section-heading"><h2>Rate catalog</h2><div className="rate-filters"><label>Profile<select value={catalogProfile} onChange={e=>setCatalogProfile(e.target.value)}><option value="all">Standard + Legacy</option><option value="standard">Standard</option><option value="legacy">Legacy</option></select></label><label>Show<select value={filter} onChange={event=>setFilter(event.target.value)}><option>All</option>{shootCategories.map(value=><option key={value}>{value}</option>)}</select></label></div></div><p className="caption">{rates.length} underlying rates retained. Price variants are grouped for display only.</p>{groupRates(rates.filter(r=>(catalogProfile==='all'||r.profile===catalogProfile)&&(filter==='All'||r.category===filter))).map(group=><RateGroup key={group[0].id} rates={group}/>)}</section>
  <section className="rate-panel"><h2>Pricing decisions</h2><p className="caption">{imports.length?'Imported observed prices are evidence only. They do not change Standard or Legacy sheet rates.':'No historical pricing dataset has been imported into this Hub database yet.'}</p>{questions.length>0&&<details><summary>{questions.length} source rows flagged for confirmation</summary><div className="pricing-questions">{questions.map((item,index)=><div className="rate-row" key={index}><span><strong>{item.item}</strong><small>{item.table} · {item.source}</small><small>{item.condition}</small><small>{item.note}</small></span><span>{item.priceCad?`CAD $${item.priceCad}`:'Custom'}</span></div>)}</div></details>}</section>
 </>;
}

export function InvoiceSuggestions({invoice,category,gmailConnected,editLine,editInvoice,onAutomaticProfile}:{invoice:InvoiceDraft;category:ShootCategory|undefined;gmailConnected:boolean;editLine:(id:string,changes:Partial<InvoiceLine>)=>void;editInvoice:(changes:Partial<InvoiceDraft>)=>void;onAutomaticProfile:(profile:InvoiceDraft['pricingProfile'])=>void}){
 const [rates,setRates]=useState<PriceSuggestion[]>([]),[custom,setCustom]=useState<CustomPricePrompt[]>([]),[emails,setEmails]=useState<EmailPriceSuggestion[]>([]),[reference,setReference]=useState<InvoiceReference|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[emailLoading,setEmailLoading]=useState(false),[targetLine,setTargetLine]=useState(invoice.lines[0]?.id||'');
 useEffect(()=>{setReference(null);let active=true;const timer=setTimeout(()=>request(`invoices/${invoice.id}/reference?client=${encodeURIComponent(invoice.client)}`).then((result:InvoiceReference)=>{if(active){setReference(result);if(invoice.pricingProfileMode==='automatic')onAutomaticProfile(result.automatic.profile);}}).catch(error=>{if(active)setError(error.message);}),250);return()=>{active=false;clearTimeout(timer);};},[invoice.id,invoice.client,invoice.pricingProfileMode]);
 useEffect(()=>{setRates([]);setCustom([]);setError('');let active=true;const timer=setTimeout(()=>{setLoading(true);request(`invoices/${invoice.id}/suggestions`,{draft:invoice}).then(result=>{if(active){setRates(result.rates);setCustom(result.custom);if(invoice.pricingProfileMode==='automatic')onAutomaticProfile(result.profile);}}).catch(error=>{if(active)setError(error.message);}).finally(()=>{if(active)setLoading(false);});},200);return()=>{active=false;clearTimeout(timer);};},[JSON.stringify(invoice),category]);
 const setClientProfile=async(profile:PricingProfile|null)=>{try{setError('');const result:InvoiceReference=await request(`invoices/${invoice.id}/client-pricing`,{client:invoice.client,profile});setReference(result);if(invoice.pricingProfileMode==='automatic')onAutomaticProfile(result.automatic.profile);}catch(error){setError((error as Error).message);}};
 const applyMatching=()=>editInvoice({lines:invoice.lines.map(line=>{const suggestion=rates.find(item=>item.lineId===line.id);return suggestion?{...line,unitPriceCents:suggestion.amountCents}:line;})});
 useEffect(()=>{setEmails([]);let active=true;if(category==='Commercial'&&gmailConnected){setEmailLoading(true);request(`invoices/${invoice.id}/email-prices`).then(result=>{if(active)setEmails(result);}).catch(error=>{if(active)setError(error.message);}).finally(()=>{if(active)setEmailLoading(false);});}return()=>{active=false;};},[invoice.id,category,gmailConnected]);
 return <section className="invoice-suggestions"><h3>Customer pricing evidence</h3>{reference?<><p className="caption">{reference.warning} {reference.automatic.reason}</p>{reference.customer&&<p><strong>{reference.customer.displayName}</strong> · imported status: {reference.customer.legacyStatus} · {reference.customer.pdfInvoices2026} PDF invoices in 2026</p>}{reference.customer&&reference.customer.profileHint!=='review'&&invoice.pricingProfile!=='review'&&reference.customer.profileHint!==invoice.pricingProfile&&<p className="custom-price">Selected {invoice.pricingProfile} pricing differs from the imported {reference.customer.profileHint} hint. Check the customer identity and agreement before saving.</p>}<div className="pricing-buttons"><span className="caption">This and future automatic drafts for this billing client:</span><button className="secondary" type="button" disabled={!reference.automatic.canSetClientOverride} aria-pressed={reference.automatic.clientOverride==='standard'} onClick={()=>setClientProfile('standard')}>Use Standard for client</button><button className="secondary" type="button" disabled={!reference.automatic.canSetClientOverride} aria-pressed={reference.automatic.clientOverride==='legacy'} onClick={()=>setClientProfile('legacy')}>Use Legacy for client</button>{reference.automatic.clientOverride&&<button className="secondary" type="button" onClick={()=>setClientProfile(null)}>Clear client override</button>}</div>{reference.historicalInvoices.length>0&&<details><summary>{reference.historicalInvoices.length} matching historical PDF invoices</summary><div className="pricing-questions">{reference.historicalInvoices.map((item,index)=><div className="rate-row" key={`${item.file}-${index}`}><span><strong>{item.number||item.file}</strong><small>{item.issued} · {item.services}</small>{!item.reconciles&&<small>Printed total did not reconcile in source extraction</small>}</span><span>{item.balance}</span></div>)}</div></details>}</>:<p className="caption">Checking imported customer history…</p>}
  <h3>Price suggestions</h3><p className="caption">Suggestions are evidence to review. Nothing is added to the invoice until you apply a price and save the draft.</p>
  {loading?<p className="caption">Checking approved rates…</p>:rates.length?<><button className="secondary" type="button" onClick={applyMatching}>Apply all {rates.length} matching sheet prices</button><p className="caption">This replaces current amounts only on matching lines. Custom quotes and unmatched lines are left unchanged.</p>{rates.map(suggestion=><div className="suggestion-row" key={suggestion.lineId}><span>{suggestion.service} · {suggestion.profile}: {money(suggestion.amountCents,suggestion.currency)}</span><button className="secondary" onClick={()=>editLine(suggestion.lineId,{unitPriceCents:suggestion.amountCents})}>Apply to line</button></div>)}</>:custom.length?null:invoice.pricingProfile==='review'&&!invoice.lines.some(line=>line.pricingProfileOverride)?<p className="custom-price">Confirm Standard or Legacy pricing on the invoice or each line to see sheet-rate suggestions.</p>:<p className="caption">No approved rate matches this profile, type, range, service and currency.</p>}
  {custom.map(prompt=><div className="custom-price" key={prompt.lineId}><strong>Custom price needed for {prompt.service}</strong><p>{prompt.note}</p><p className="caption">Enter the confirmed amount on the invoice line below.</p></div>)}
  {category==='Commercial'&&<div className="email-suggestions"><h3>Commercial quotes in Gmail</h3>{!gmailConnected?<p className="caption">Connect info@jonathanfolk.ca in Connections to search for quote emails.</p>:<><p className="caption">Searches recent matching messages when this draft opens. Verify the client and scope of each quote before applying a price.</p>{emailLoading?<p className="caption">Searching Gmail…</p>:emails.length?<><label>Apply to invoice line<select value={targetLine} onChange={event=>setTargetLine(event.target.value)}>{invoice.lines.map(line=><option key={line.id} value={line.id}>{line.description}</option>)}</select></label>{emails.map((suggestion,index)=><div className="email-result" key={`${suggestion.messageId}-${index}`}><strong>{money(suggestion.amountCents,suggestion.currency)} · {suggestion.subject||'Email quote'}</strong><small>{suggestion.from} · {suggestion.date}</small><p>{suggestion.excerpt}</p><div className="actions"><a href={`https://mail.google.com/mail/u/0/#all/${encodeURIComponent(suggestion.threadId)}`} target="_blank" rel="noopener noreferrer">Open email</a><button className="secondary" disabled={!targetLine||suggestion.currency!==invoice.currency} onClick={()=>editLine(targetLine,{unitPriceCents:suggestion.amountCents})}>Apply price</button></div></div>)}</>:<p className="caption">No explicit CAD or USD amounts were found in the matching emails.</p>}</>}</div>}
  {error&&<p className="error-text" role="alert">{error}</p>}
 </section>;
}
