import React,{useState} from 'react';
import {commercialSubtypes,type InvoiceDraft,type InvoiceLine,type Rate,type SortDetails} from '../server/types';

export function TrashIcon(){return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" aria-hidden="true"><path d="M4 7h16m-14 0 1 14h10l1-14M9 7V4h6v3m-5 4v7m4-7v7"/></svg>;}
export function StatusRibbon({label,tone='review'}:{label:string;tone?:'review'|'scheduled'|'unconfirmed'|'done'|'muted'}){return <span className={`status-ribbon ribbon-${tone}`}>{label}</span>;}
export function StatusLegend(){return <details className="status-legend"><summary>Status legend</summary><div><span><StatusRibbon label="Check booking"/><small>Details need review</small></span><span><StatusRibbon label="Confirmed" tone="scheduled"/><small>Booking confirmed; completion still needs checking</small></span><span><StatusRibbon label="Unconfirmed" tone="unconfirmed"/><small>Hold, tentative, weather or date pending</small></span><span><StatusRibbon label="Reviewed / ready" tone="done"/><small>Follow the text label for the workflow stage</small></span><span><StatusRibbon label="Cancelled / dismissed" tone="muted"/></span></div></details>;}
export function CommercialFields({details,onChange}:{details:SortDetails;onChange:(d:SortDetails)=>void}){
 const change=(next:SortDetails)=>onChange({...details,...next});
 return <div className="commercial-sort"><label>Commercial category<select value={details.commercialSubtype||''} onChange={e=>onChange({commercialSubtype:e.target.value as SortDetails['commercialSubtype'],commercialPackage:e.target.value==='Developer Residential'?'staged':'short',imageCount:5,retouchCount:0,twilight:false,drone:false})}><option value="">Choose a category</option>{commercialSubtypes.map(x=><option key={x}>{x}</option>)}</select></label>
  {details.commercialSubtype==='Developer Residential'&&<label>Property condition<select value={details.commercialPackage} onChange={e=>change({commercialPackage:e.target.value as SortDetails['commercialPackage']})}><option value="staged">Staged · $750</option><option value="vacant">Vacant · $350</option></select></label>}
  {details.commercialSubtype?.startsWith('Interior Design')&&<><label>Visit<select value={details.commercialPackage} onChange={e=>change({commercialPackage:e.target.value as SortDetails['commercialPackage']})}><option value="short">Short visit · $750</option><option value="half">4 hours on site · $1,250</option></select></label><small>{details.commercialSubtype==='Interior Design S'?'No image cap. Confirm short-visit duration.':'20/30-image allowances versus no cap are pending your decision. A terms review will remain open.'}</small></>}
  {details.commercialSubtype==='Commercial Exterior'&&<><div className="invoice-fields"><label>Edited images · $20 each<input type="number" min="1" max="100" value={details.imageCount} onChange={e=>change({imageCount:Number(e.target.value)})}/></label><label>Retouched images · +$25 each<input type="number" min="0" max={details.imageCount} value={details.retouchCount} onChange={e=>change({retouchCount:Number(e.target.value)})}/></label></div><label className="inline-check"><input type="checkbox" checked={!!details.twilight} onChange={e=>change({twilight:e.target.checked})}/>After-hours twilight · +$150</label><label className="inline-check"><input type="checkbox" checked={!!details.drone} onChange={e=>change({drone:e.target.checked})}/>Drone launch · +$200</label><small>$450 on-site base. Drone includes complimentary airspace unlocking. Prices are CAD, before tax.</small><strong>Draft subtotal: ${450+(details.imageCount||0)*20+(details.retouchCount||0)*25+(details.twilight?150:0)+(details.drone?200:0)}</strong></>}
  {details.commercialSubtype==='Misc Commercial'&&<small>Custom scope and price. Enter the agreed amount in the draft.</small>}
 </div>;
}
export function AddServicePicker({rates,invoice,onAdd}:{rates:Rate[];invoice:InvoiceDraft;onAdd:(line:InvoiceLine)=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[profile,setProfile]=useState(invoice.pricingProfile==='legacy'?'legacy':'standard'),[quantity,setQuantity]=useState(1);
 const options=rates.filter(r=>r.profile===profile&&r.currency===invoice.currency&&`${r.service} ${r.category} ${r.squareFootageRange}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="service-picker"><button type="button" className="secondary" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Close service picker':'+ Add saved service'}</button>{open&&<div className="service-picker-body"><label>Find a service<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Drone, staging, floor plan…"/></label><div className="invoice-fields"><label>Rate sheet<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="standard">Standard</option><option value="legacy">Legacy</option></select></label><label>Quantity<input type="number" min="1" max="100" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div><div className="service-picker-results">{options.map(rate=><button type="button" key={rate.id} disabled={invoice.lines.length>=25||!Number.isInteger(quantity)||quantity<1||quantity>100} onClick={()=>{onAdd({id:crypto.randomUUID(),description:rate.service,quantity,unitPriceCents:rate.unitPriceCents,pricingProfileOverride:rate.profile,rateSource:rate.source});setOpen(false);}}><span>{rate.service}<small>{rate.squareFootageRange||rate.category} · {rate.source}</small></span><span>{new Intl.NumberFormat('en-CA',{style:'currency',currency:rate.currency}).format(rate.unitPriceCents/100)} / {rate.unit}</span></button>)}{!options.length&&<p className="caption">No fixed rate found. Use Add line for a custom quote.</p>}</div><small>Choose the requested package and quantity. Adding the same service twice is a separate charge; review existing lines first.</small></div>}</div>;
}
